### PR TITLE
Add a message about the new templates directory

### LINKED ISSUE #18: Cannot install the Symfony templates
I'm using PHPStorm 2018.1.6 and when I download the files and try to put them in the config dir, the frontend live templates are visible but not the Symfony ones, I can't figure out where is the issue exactly.

Any idea?

### PR DESCRIPTION
**Pull request by Pierstoval**
Fixes #18 possibly 😄

### CODE REVIEW

**Comment by MolloKhan** [comment]
Hey @Pierstoval, thanks for the PR!

If someone can confirm that this fixes the problem, I'd be happy to merge it :)

**Comment by Pierstoval** [comment]
I found the real issue I had and it's now fixed thanks to the last commit I made to this documentation 👍

**Comment by MolloKhan** [comment]
Hey @Pierstoval, thank you very much for your contribution, we really appreciate this. I hope soon I'll find the time to double check your solution, so then I can merge it :)

Cheers!

**Review by bocharsky-bw — APPROVED** [review]
This is just a note, and if it works for a few people - I think it can be merged 👍 Anyway, we can tweak it later or add more notes for other odd cases

**Comment by Pierstoval** [comment]
First solution seemed to work for one person in #18 and the second worked for me, I know this is not a concrete proof of success, but it's an example of working solutions under certain conditions 😄

**Comment by MolloKhan** [comment]
Cool, let's merge it then!

**Pull request merged**
