### PR TITLE
Add `findall` template

### PR DESCRIPTION
**Pull request by roukmoute**

### CODE REVIEW

**Comment by weaverryan** [comment]
Hey @roukmoute!

Check out the existing `repofind` template. We should make sure these work the same way. Also, I think we should try to make each template a single line. So in this case - we should do everything in one line (like `repofind` does) instead of setting a variable and using it. They may already have an `$em` variable... we don't know - so I think it makes sense to minimize our "footprint".

Thanks!

P.S. This also looks like it needs a rebase.

**Comment by roukmoute** [comment]
Hi @weaverryan !
I finally took the time to answer you.
I would like to propose to replace `repofind` (it's so long !).
I work on the assumption that if you call the `entity manager`, generally you call a `finder`.
So why type two shortcuts when you know only one enough ?

On my own shortcuts i use `em` shortcut to do the same proposition:
- The `$END$` is not an accident. You could remove easily `all` with `Alt+Tab` to write near method.
- You do not generate false result, on typing `em`, if you expand with `tab`.

And conversely, more globaly, I think it is useless to have too shortcuts.
Impossible to remember everything.
We need shortcuts are short and simple.

What do you think ?

**Comment by roukmoute** [comment]
snif :cry:

**Comment by weaverryan** [comment]
Hey @roukmoute you should re-open! I just haven't had time to get to this yet - but it's on my list! I spread across many repos - but I appreciate your work here!

**Comment by weaverryan** [comment]
Hey Mathias!

Ok, I hear your points. Here's what I'm thinking:

1) I still don't want the `$em =` at the beginning of the snippet because if I use `findAll` twice, then I would have 2 of these, which just isn't necessary. But I don't think that's really a problem - we can just do it in one (chained) line with `$this->getDoctrine()->getRepository('...')->findAll()` - it's actually less code anyways.

2) I like that you added the `$ENTITIES$ =` in front of this - that's better than my `repofind`

3) We should replace `repofind` with just `find` and make it have `$ENTITY$ =` at the beginning. Something like this

```
$ENTITY$ = $this->getDoctrine()
    ->getRepository('$REPO$')->find$METHOD$($ARG$);
```

What do you think?

**Pull request closed without merging**
